---
title: "Introduction"
subtitle: "Day 4: Trait, time lags, and measurement error"
editor: source
---

In this computer lab are going to analyze the same data that were used in the Hamaker et al. (2015) paper and were presented in the lecture. The goals of these exercises are to get some experience with fitting (random intercept) cross-lagged panel models, interpreting their results, and comparing them. Here, we focus on the relationship between *Parental Responsiveness* and *Adolescents' Depressive Symptomatology* (note, in the lecture the focus was on a different concept, namely *Parental Psychological Control*).

The data (means, standard deviations, and the correlation matrix) are included in the file `Soenens.dat` on SURFdrive. The number of observations is 396. The data command for these data should be:

```default
DATA:       
  TYPE = MEANS STDEVIATIONS CORRELATION;   
  FILE = Soenens.dat;
  NOBSERVATIONS = 396;
```

The variable command should be:

```default
VARIABLE:   
  NAMES = PsCon1-PsCon3 Res1-Res3 BeCon1-BeCon3 Dep1-Dep3;
  USEVARIABLES = Res1 Dep1 Res2 Dep2 Res3 Dep3;
```

Do the exercises. You can navigate through them using the left-hand menu or the arrows on left- and right-hand side of this screen. Answers are included below each exercise. The Mplus input files can found in the SURFdrive folder.
