---
title: "Part 2: The RI-CLPM"
subtitle: "Day 4: Trait, time lags, and measurement error"
editor: source
bibliography: references.bib
---

In the second part of the computer lab, we continue analyzing the data that were used in the @hamaker_critique_2015 paper and were presented in the lecture. However, now we explore cross-lagged relations while controlling for stable, between-person differences.

## The RI-CLPM

### Exercise 3A
Specify the RI-CLPM for these data (without any constraints on the lagged parameters over time). Discuss the model fit.

::: {.callout-caution collapse="true"}
### Answer
The input for these models are in `exercise3A.inp`. This model fits very well; however, it only has 1 *df*, so it is not doing much for data reduction.
:::

### Exercise 3B
Specify the RI-CLPM with the constraints on the grand means at each occasions. Again, please do not constrain the mean of `Dep1`, however, as this constraint proved untenable in exercise 3.

::: {.callout-caution collapse="true"}
### Answer
The input for these models are in `exercise3B.inp`. This model has an acceptable (RMSEA, $\chi^{2}$) to good (CFI and TLI) fit.  Comparing it to the previous model, we get a chi-square difference test of $\Delta\chi^{2} = 9.590 - 0.84 = 8.75$, $\Delta$*df* = 4 - 1 = 3, $p = .0328$. This implies that the constraints we impose on the means are untenable (they lead to a significant worsening of model fit). You might therefore decide to ultimately not impose these constraints. However, for didactical reasons, we continue with these constraints in place in the next exercise. 
:::

### Exercise 3C
Add the constraints on the lagged parameters to the previous model.

::: {.callout-caution collapse="true"}
### Answer
The input for these models are in `exercise3C.inp`. This model fits okay (depending on the measure). Comparing it to the previous model, we get $\Delta\chi^{2} = 19.74 - 9.59 = 8.15$, $\Delta$*df* = 8 - 4 = 4, $p = .0379$. Again, this implies that constraining the lagged effects to be time-invariant is untenable (it leads to a significant worsening of model fit).
:::

### Exercise 3D
Compare all the models so far simultaneously, using the AIC and BIC. Which model is selected?

::: {.callout-caution collapse="true"}
### Answer
Based on the AIC, the RI-CLPM without any constraints provides the closest fit to the data, followed by the two other RI-CLPMs (and the adjusted means model). Based on the BIC, the RI-CLPM with constraints on the means and the lagged parameters is superior to the other models.

| Exercise | Input file   | AIC    | BIC   |
| -------- | :----------- | :----: | :----:
| 1        | exercise1A.inp    | 9451   | 9543 |
| 3        | exercise1C.inp   | 9442   | 9538 |
| 6        | exercise2A.inp and exercise2B.inp | 9494 | 9586 |
| 7        | exercise2E.inp | 9495   | 9575 | 
| 8        | exercise2F.inp | 9499   | 9563 | 
| 9        | exercise3A.inp   | **9438** | 9541 | 
| 10       | exercise3B.inp  | 9441   | 9533 | 
| 11       | exercise3C.inp  | 9443   | **9518** | 
:::

## Prepartion consultation day
Once you have finished all the exercises, you can start preparing for the consultation day. Below are a couple of tips and questions that can help you in making the most out of this day.

1. Can you translate your research question into a SEM diagram? A SEM diagram can greatly help communicating to others about your research question, and help you with setting up the model in Mplus. 
2. In your SEM diagram, which arrows provide a direct answer to your research question (i.e., which arrows are of core interest)?  
3. Do you expect measurement error in your measurement, and has this been included in the path diagram? 
4. In case of a longitudinal study design, how much time has passed between repeated measures? Does this time frame make theoretical sense (or is it too long/too short for you to capture your effect of interest)? 
5. Are there likely to be stable, between-person differences in your time-varying variables? Is this taken into account in the SEM diagram? 

